dependencies:
    - smartcontractkit/chainlink-brownie-contracts@0.4.0
    - aave/protocol-v2@1.0.1
compiler:
    solc:
        remappings:
            - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0"
            - "@aave=aave/protocol-v2@1.0.1"
dotenv: .env
networks:
  goerli:
    weth_token: '0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6'
  mainnet-fork:
    weth_token: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
  mainent:
    weth_token: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
wallets:
  from_key: ${PRIVATE_KEY}

